%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/alumno.upv.es/almousa/CMCP/Trabajo/plotsmatlab/Medidas Trabajo CMCP.xlsx
%    Worksheet: Plots
%
% Auto-generated by MATLAB on 17-Nov-2021 17:32:13

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "Plots";
opts.DataRange = "B30:J36";

% Specify column names and types
opts.VariableNames = ["Procesadores", "TiempoFuerte", "TiempoDebil", "SpeedupFuerte", "SpeedupDebil", "CosteFuerte", "Overhead", "EficienciaFuerte","EficienciaDebil"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double","double"];

% Import the data
OpenMP_MPI = readtable("/home/alumno.upv.es/almousa/CMCP/Trabajo/plotsmatlab/Medidas Trabajo CMCP.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts